version: "3.7"
services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - ./database_schema:/docker-entrypoint-initdb.d
  java:
    build: .
    ports:
      - "8081:8080"